//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by PhxWorldEditor.rc
//
#define IDD_GEN_TERRAIN                 9
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define ID_VIEW_HEIGHTEDIT              101
#define ID_VIEW_TEXTURE_LAYER           102
#define ID_VIEW_Model3D                 103
#define ID_VIEW_MODEL3D                 103
#define IDS_VIEW_NODELIST               104
#define IDR_POPUP_EDIT                  119
#define ID_STATUSBAR_PANE1              120
#define ID_STATUSBAR_PANE2              121
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define IDS_TOOLBAR_STANDARD            124
#define IDS_TOOLBAR_CUSTOMIZE           125
#define ID_VIEW_CUSTOMIZE               126
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAME_256               129
#define IDR_PhxWorldEditorTYPE          130
#define ID_WINDOW_MANAGER               131
#define ID_VIEW_FILEVIEW                133
#define ID_VIEW_CLASSVIEW               134
#define ID_PROPERTIES                   135
#define ID_OPEN                         136
#define ID_OPEN_WITH                    137
#define ID_DUMMY_COMPILE                138
#define ID_CLASS_ADD_MEMBER_FUNCTION    139
#define ID_CLASS_ADD_MEMBER_VARIABLE    140
#define ID_CLASS_DEFINITION             141
#define ID_CLASS_PROPERTIES             142
#define ID_NEW_FOLDER                   143
#define ID_SORT_MENU                    144
#define ID_SORTING_GROUPBYTYPE          145
#define ID_SORTING_SORTALPHABETIC       146
#define ID_SORTING_SORTBYTYPE           147
#define ID_SORTING_SORTBYACCESS         148
#define ID_VIEW_OUTPUTWND               149
#define ID_VIEW_PROPERTIESWND           150
#define ID_SORTPROPERTIES               151
#define ID_PROPERTIES1                  152
#define ID_PROPERTIES2                  153
#define ID_EXPAND_ALL                   154
#define IDS_FILE_VIEW                   155
#define IDS_CLASS_VIEW                  156
#define IDS_OUTPUT_WND                  157
#define IDS_PROPERTIES_WND              158
#define IDI_FILE_VIEW                   161
#define IDI_FILE_VIEW_HC                162
#define IDI_CLASS_VIEW                  163
#define IDI_CLASS_VIEW_HC               164
#define IDI_OUTPUT_WND                  165
#define IDI_OUTPUT_WND_HC               166
#define IDI_PROPERTIES_WND              167
#define IDI_PROPERTIES_WND_HC           168
#define IDR_EXPLORER                    169
#define IDB_EXPLORER_24                 170
#define IDR_SORT                        171
#define IDB_SORT_24                     172
#define IDR_POPUP_SORT                  173
#define IDR_POPUP_EXPLORER              174
#define IDB_FILE_VIEW                   175
#define IDB_FILE_VIEW_24                176
#define IDB_CLASS_VIEW                  177
#define IDB_CLASS_VIEW_24               178
#define IDR_MENU_IMAGES                 179
#define IDB_MENU_IMAGES_24              180
#define ID_TOOLS_MACRO                  181
#define IDR_OUTPUT_POPUP                182
#define IDR_PROPERTIES                  183
#define IDB_PROPERTIES_HC               184
#define IDR_THEME_MENU                  200
#define ID_SET_STYLE                    201
#define ID_VIEW_APPLOOK_WIN_2000        205
#define ID_VIEW_APPLOOK_OFF_XP          206
#define ID_VIEW_APPLOOK_WIN_XP          207
#define ID_VIEW_APPLOOK_OFF_2003        208
#define ID_VIEW_APPLOOK_VS_2005         209
#define ID_VIEW_APPLOOK_VS_2008         210
#define ID_VIEW_APPLOOK_OFF_2007_BLUE   215
#define ID_VIEW_APPLOOK_OFF_2007_BLACK  216
#define ID_VIEW_APPLOOK_OFF_2007_SILVER 217
#define ID_VIEW_APPLOOK_OFF_2007_AQUA   218
#define ID_VIEW_APPLOOK_WINDOWS_7       219
#define IDS_BUILD_TAB                   300
#define IDS_DEBUG_TAB                   301
#define IDS_FIND_TAB                    302
#define IDS_EXPLORER                    305
#define IDS_EDIT_MENU                   306
#define IDD_HEIGHTEDIT_DLG              311
#define IDD_TERRAIN_TEXTURE_DLG         313
#define IDR_MMTOOLBAR                   314
#define IDD_ADVANCETEX_DLG              316
#define IDD_MODEL3D_DLG                 317
#define IDD_NODELIST                    318
#define IDD_MOVEMENT_DLG                319
#define IDD_DIALOG1                     320
#define IDD_ENVIRONMENT_DLG             320
#define IDC_EDIT1                       1000
#define IDC_EDIT2                       1001
#define IDC_EDIT3                       1002
#define IDC_RADIO1                      1003
#define IDC_EDIT10                      1003
#define IDC_RADIO2                      1004
#define IDC_EDIT11                      1004
#define IDC_RADIO3                      1005
#define IDC_EDIT9                       1005
#define IDC_RECT_HEIGHT                 1005
#define IDC_EDIT4                       1006
#define IDC_BUTTON1                     1007
#define IDC_EDIT12                      1007
#define IDC_RADIO4                      1008
#define IDC_EDIT13                      1008
#define IDC_RADIO5                      1009
#define IDC_EDIT14                      1009
#define IDC_EDIT5                       1010
#define IDC_EDIT15                      1010
#define IDC_EDIT6                       1011
#define IDC_EDIT7                       1012
#define IDC_EDIT8                       1013
#define IDC_MAXHEIGHT                   1015
#define IDC_HEDT_STEPSIZE               1016
#define IDC_APPLY_HGTSET                1017
#define IDC_RADIUS                      1018
#define IDC_RECT_WIDTH                  1019
#define IDC_RADIO6                      1020
#define IDC_RADIO7                      1021
#define IDC_TEXLIST                     1022
#define IDC_DELTEX                      1023
#define IDC_ADVTEX                      1024
#define IDC_USETEX                      1025
#define IDC_ADDTEX                      1026
#define IDC_FROM                        1027
#define IDC_TO                          1028
#define IDC_PAINT_RADIUS                1029
#define IDC_LIST1                       1030
#define IDC_DELOBJECT                   1031
#define IDC_ADDOBJECT                   1035
#define IDC_TREE2                       1037
#define IDC_ADDMD5                      1038
#define IDC_CHECK1                      1039
#define IDC_SLIDER1                     1040
#define IDC_TEXALPHA                    1041
#define IDC_UNPAINT                     1042
#define IDC_SCALE_OBJ                   1043
#define ID_OBJECT_3DMODEL               32771
#define ID_OBJECT_LIGHT                 32772
#define ID_OBJECT_REFERENCEPOINTS       32773
#define ID_TERRAIN_GE                   32774
#define ID_TERRAIN_TEXTURELAYER         32775
#define ID_TERRAIN_EDITHEIGHT           32776
#define ID_CAMFREE                      32777
#define ID_CAMPAN                       32778
#define ID_CAMEDTHGT                    32780
#define ID_CAMPNTTRN                    32781
#define ID_BUTTON32782                  32782
#define ID_MMADD                        32782
#define ID_FILE_CLOSE32783              32783
#define ID_SETTINGS_MOVEMENT            32784
#define ID_FILE_XAVE                    32785
#define ID_SETTINGS_ENVIRONMENT         32786

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        321
#define _APS_NEXT_COMMAND_VALUE         32787
#define _APS_NEXT_CONTROL_VALUE         1044
#define _APS_NEXT_SYMED_VALUE           310
#endif
#endif
